sudo: false
language: ruby
rvm:
  - 2.1.2
  - 2.2.2
  - 2.3.0
gemfile:
  - gemfiles/jr0.6.gemfile
  - gemfiles/jr0.7.gemfile
  - gemfiles/jr0.8.gemfile
  - Gemfile
before_install: gem install bundler -v 1.13.6
